
services:
   easyform:
      image: m4rkus28/easyform:latest
      container_name: easyform
      env_file:
        - .env
      ports:
        - "7109:8080"
      restart: always
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
      environment:
        - WORKERS=1
